version: "3.9"

services:
  my-apache-image:
    image: my-apache2-image
    networks:
      - int
      - ext
    ports:
      - 8081:80

  chronograf:
    image: chronograf
    networks:
      - int
      - ext
    ports:
      - 8082:8888

networks:
  int:
    external: false

  ext:
    driver: bridge